# Generated by Django 4.2 on 2023-07-04 09:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chatnotification",
            options={
                "verbose_name": "Уведомление",
                "verbose_name_plural": "Уведомления",
            },
        ),
        migrations.AlterModelOptions(
            name="message",
            options={
                "ordering": ("-created_at",),
                "verbose_name": "Сообщение",
                "verbose_name_plural": "Сообщения",
            },
        ),
        migrations.AlterModelOptions(
            name="room",
            options={
                "verbose_name": "Чат/Комната",
                "verbose_name_plural": "Чаты/Комнаты",
            },
        ),
        migrations.AlterField(
            model_name="chatnotification",
            name="author",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="author",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор(опционально)",
            ),
        ),
        migrations.AlterField(
            model_name="chatnotification",
            name="is_seen",
            field=models.BooleanField(default=False, verbose_name="Просмотрено"),
        ),
        migrations.AlterField(
            model_name="chatnotification",
            name="text",
            field=models.TextField(null=True, verbose_name="Текст уведомления"),
        ),
        migrations.AlterField(
            model_name="chatnotification",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reciever",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Получатель уведомления",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="author_messages",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="chat.room",
                verbose_name="Чат/комната",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="text",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Текст сообщения"
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="author_room",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор",
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="receiver",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="receiver_room",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Участник чата",
            ),
        ),
    ]
