# Generated by Django 4.2 on 2023-07-21 08:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("chat", "0002_alter_chatnotification_options_alter_message_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatnotification",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reciever",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Получатель уведомления",
            ),
        ),
    ]
