# Generated by Django 4.2 on 2023-07-21 09:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("chat", "0003_alter_chatnotification_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatnotification",
            name="author",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="author",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор(опционально)",
            ),
        ),
        migrations.AlterField(
            model_name="chatnotification",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reciever",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Получатель уведомления",
            ),
        ),
    ]
