# Generated by Django 4.2 on 2023-08-10 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0005_alter_chatnotification_author_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="is_read",
            field=models.BooleanField(blank=True, null=True, verbose_name="Прочитано"),
        ),
    ]
