# Generated by Django 4.2 on 2023-08-15 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0007_room_content_type_room_object_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "Новый"),
                    ("decline", "Отклонен"),
                    ("accepted", "Принят"),
                ],
                default="new",
                max_length=32,
                verbose_name="Статус чата",
            ),
        ),
    ]
