# Generated by Django 4.2 on 2023-08-16 08:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("chat", "0008_room_status"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="room",
            unique_together={("author", "receiver", "content_type", "object_id")},
        ),
    ]
