# Generated by Django 4.2 on 2023-08-21 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("image", "0018_alter_file_options_alter_image_options"),
        ("chat", "0010_alter_room_content_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="images",
            field=models.ManyToManyField(
                blank=True, related_name="message_images", to="image.image"
            ),
        ),
    ]
