# Generated by Django 4.2 on 2023-08-22 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("image", "0018_alter_file_options_alter_image_options"),
        ("chat", "0011_message_images"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="files",
            field=models.ManyToManyField(
                blank=True, related_name="message_files", to="image.file"
            ),
        ),
    ]
