# Generated by Django 4.2 on 2023-08-23 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("chat", "0012_message_files"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="content_type",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to=models.Q(
                    models.Q(("app_label", "vacancy"), ("model", "candidate")),
                    models.Q(("app_label", "offer"), ("model", "candidateStartup")),
                    models.Q(("app_label", "vacancy"), ("model", "workteam")),
                    _connector="OR",
                ),
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="content_type",
                to="contenttypes.contenttype",
            ),
        ),
    ]
