# Generated by Django 4.2 on 2023-08-25 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0013_alter_room_content_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="text",
            field=models.TextField(
                blank=True, null=True, verbose_name="Текст сообщения"
            ),
        ),
    ]
