# Generated by Django 4.2 on 2023-09-06 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0014_alter_message_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="status",
            field=models.CharField(
                choices=[("active", "Активный"), ("banned", "Забанен")],
                default="active",
                max_length=32,
                verbose_name="Статус чата",
            ),
        ),
    ]
