# Generated by Django 4.2 on 2023-09-11 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0015_alter_room_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="ban_status",
            field=models.BooleanField(blank=True, null=True, verbose_name="Бан статус"),
        ),
    ]
