# Generated by Django 4.2 on 2023-04-24 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Achievements",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "accelerator",
                    models.TextField(blank=True, null=True, verbose_name="Акселератор"),
                ),
                (
                    "conference",
                    models.TextField(blank=True, null=True, verbose_name="Конференция"),
                ),
                (
                    "hackathon",
                    models.TextField(blank=True, null=True, verbose_name="Хакатон"),
                ),
                (
                    "mass_media",
                    models.TextField(blank=True, null=True, verbose_name="Массмедиа"),
                ),
                (
                    "awards",
                    models.TextField(blank=True, null=True, verbose_name="Награды"),
                ),
                (
                    "other",
                    models.TextField(blank=True, null=True, verbose_name="Другое"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Industries",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=32, verbose_name="Название")),
            ],
        ),
        migrations.CreateModel(
            name="Links",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "app_store",
                    models.CharField(
                        blank=True, max_length=32, null=True, verbose_name="Аппстор"
                    ),
                ),
                (
                    "google_play",
                    models.CharField(
                        blank=True, max_length=32, null=True, verbose_name="Гуглплэй"
                    ),
                ),
                (
                    "twitter",
                    models.CharField(
                        blank=True, max_length=32, null=True, verbose_name="Твиттер"
                    ),
                ),
                (
                    "telegram",
                    models.CharField(
                        blank=True, max_length=32, null=True, verbose_name="Телеграм"
                    ),
                ),
                (
                    "youtube",
                    models.CharField(
                        blank=True, max_length=32, null=True, verbose_name="Ютуб"
                    ),
                ),
                (
                    "discord",
                    models.CharField(
                        blank=True, max_length=32, null=True, verbose_name="Дискорд"
                    ),
                ),
                (
                    "facebook",
                    models.CharField(
                        blank=True, max_length=32, null=True, verbose_name="Фэйсбук"
                    ),
                ),
                (
                    "instagram",
                    models.CharField(
                        blank=True, max_length=32, null=True, verbose_name="Инстаграм"
                    ),
                ),
                (
                    "linkedin",
                    models.CharField(
                        blank=True, max_length=32, null=True, verbose_name="Линкедин"
                    ),
                ),
                (
                    "medium",
                    models.CharField(
                        blank=True, max_length=32, null=True, verbose_name="Медиум"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Purpose",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "problem",
                    models.TextField(blank=True, null=True, verbose_name="Акселератор"),
                ),
                (
                    "decision",
                    models.TextField(blank=True, null=True, verbose_name="Конференция"),
                ),
            ],
        ),
        migrations.RenameField(
            model_name="startup",
            old_name="user",
            new_name="owner",
        ),
        migrations.AddField(
            model_name="startup",
            name="foundation_year",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="startup",
            name="name",
            field=models.CharField(default=1, max_length=32, verbose_name="Название"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="startup",
            name="short_description",
            field=models.TextField(blank=True, null=True, verbose_name="Описание"),
        ),
        migrations.AddField(
            model_name="startup",
            name="url",
            field=models.CharField(
                blank=True, max_length=32, null=True, verbose_name="Урл"
            ),
        ),
    ]
