# Generated by Django 4.2 on 2023-04-25 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("image", "0010_rename_image_background_background_and_more"),
        ("profiles", "0002_achievements_industries_links_purpose_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BusinessType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=32, verbose_name="Название")),
            ],
        ),
        migrations.CreateModel(
            name="SaleRegions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32, verbose_name="Название")),
            ],
        ),
        migrations.AddField(
            model_name="industries",
            name="type",
            field=models.CharField(
                choices=[("blockchain", "Блокчейн"), ("other", "Остальное")],
                default=1,
                max_length=25,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="startup",
            name="achievements",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="profiles.achievements",
                verbose_name="Достижения",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="startup",
            name="already_distributed",
            field=models.IntegerField(
                blank=True, default=0, null=True, verbose_name="Ранние вложения"
            ),
        ),
        migrations.AddField(
            model_name="startup",
            name="background",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="image.background",
                verbose_name="Бэкграунд",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="startup",
            name="business_model",
            field=models.CharField(
                choices=[
                    ("B2B", "Business to Business"),
                    ("B2C", "Business to consumer"),
                    ("B2G", "Business to Government"),
                    ("C2B", "Consumer to business"),
                    ("C2C", "Consumer to consumer"),
                    ("C2G", "Consumer to Government"),
                    ("SAAS", "Software on Demand"),
                ],
                default=1,
                max_length=25,
                verbose_name="Бизнес модель",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="startup",
            name="capital_offer",
            field=models.IntegerField(
                blank=True, default=0, null=True, verbose_name="Предложение инвестору"
            ),
        ),
        migrations.AddField(
            model_name="startup",
            name="development_stage",
            field=models.CharField(
                choices=[
                    ("Project Start", "Старт проекта"),
                    ("Working on the product", "Работа над продуктом"),
                    ("Entering the market", "Выход на рынок"),
                    ("Growth and scaling", "Рост и масштабирование"),
                ],
                default=1,
                max_length=32,
                verbose_name="Стадия разработки",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="startup",
            name="headquartered",
            field=models.CharField(
                default=1, max_length=32, verbose_name="Штаб-квартира"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="startup",
            name="industries",
            field=models.ManyToManyField(
                blank=True,
                related_name="industries",
                to="profiles.industries",
                verbose_name="Индустрии",
            ),
        ),
        migrations.AddField(
            model_name="startup",
            name="is_registered",
            field=models.BooleanField(
                default=False, verbose_name="Уже зарегистрирована"
            ),
        ),
        migrations.AddField(
            model_name="startup",
            name="logo",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="image.logo",
                verbose_name="Логотип",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="startup",
            name="market_size",
            field=models.TextField(default=1, verbose_name="Размер рынка"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="startup",
            name="pitch_presentation",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="image.file",
                verbose_name="Файл презентации",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="startup",
            name="profit",
            field=models.IntegerField(
                blank=True, default=0, null=True, verbose_name="Профит"
            ),
        ),
        migrations.AddField(
            model_name="startup",
            name="purpose",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="profiles.purpose",
                verbose_name="Цель",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="startup",
            name="registration_country",
            field=models.CharField(
                choices=[
                    ("Northern America", "Северная Америка"),
                    ("Central America & Caribbean", "Центральная Америка и Карибы"),
                    ("South America", "Южная Америка"),
                    ("Nordics & Baltics", "Северо-Балтийск"),
                    ("Western Europe", "Западная Европа"),
                    ("Southern Europe", "Южная Европа"),
                    ("Eastern Europe & Russia", "Восточная Европа и Россия"),
                    (
                        "Northern Africa & Middle East",
                        "Северная Африка и Ближний Восток",
                    ),
                    ("Africa", "Африка"),
                    ("Asia", "Азия"),
                    ("Worldwide", "Мировой"),
                    (
                        "Australia, New Zealand & Oceania",
                        "Австралия, Новая зеландия и Океания",
                    ),
                ],
                default=1,
                max_length=50,
                verbose_name="Статус",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="startup",
            name="required_founding",
            field=models.IntegerField(
                blank=True,
                default=0,
                null=True,
                verbose_name="Требуемое финансирование",
            ),
        ),
        migrations.AddField(
            model_name="startup",
            name="stage",
            field=models.CharField(
                choices=[("Angel", "Ангел"), ("Pre-Seed", "Пресид"), ("Seed", "Сид")],
                default=1,
                max_length=10,
                verbose_name="Стадия",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="startup",
            name="business_type",
            field=models.ManyToManyField(
                blank=True,
                related_name="business",
                to="profiles.businesstype",
                verbose_name="Тип бизнеса",
            ),
        ),
        migrations.AddField(
            model_name="startup",
            name="regions",
            field=models.ManyToManyField(
                blank=True,
                related_name="industries",
                to="profiles.saleregions",
                verbose_name="Регионы продажи",
            ),
        ),
    ]
