# Generated by Django 4.2 on 2023-04-26 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0003_businesstype_saleregions_industries_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="startup",
            name="already_distributed",
            field=models.IntegerField(default=0, verbose_name="Ранние вложения"),
        ),
        migrations.AlterField(
            model_name="startup",
            name="capital_offer",
            field=models.IntegerField(default=0, verbose_name="Предложение инвестору"),
        ),
        migrations.AlterField(
            model_name="startup",
            name="is_registered",
            field=models.BooleanField(verbose_name="Уже зарегистрирована"),
        ),
        migrations.AlterField(
            model_name="startup",
            name="required_founding",
            field=models.IntegerField(
                default=0, verbose_name="Требуемое финансирование"
            ),
        ),
    ]
