# Generated by Django 4.2 on 2023-04-26 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0004_alter_startup_already_distributed_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="industries",
            name="title",
            field=models.CharField(max_length=50, verbose_name="Название"),
        ),
    ]
