# Generated by Django 4.2 on 2023-04-26 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0005_alter_industries_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="startup",
            name="profit",
            field=models.IntegerField(default=0, verbose_name="Профит"),
        ),
    ]
