# Generated by Django 4.2 on 2023-04-27 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0006_alter_startup_profit"),
    ]

    operations = [
        migrations.AddField(
            model_name="startup",
            name="social_links",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="profiles.links",
                verbose_name="Социальные сети",
            ),
            preserve_default=False,
        ),
    ]
