# Generated by Django 4.2 on 2023-04-27 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0007_startup_social_links"),
    ]

    operations = [
        migrations.AddField(
            model_name="startup",
            name="detailed_description",
            field=models.TextField(default=1, verbose_name="Детальное описание"),
            preserve_default=False,
        ),
    ]
