# Generated by Django 4.2 on 2023-04-30 10:14

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("image", "0012_alter_background_background_alter_logo_logo"),
        ("profiles", "0008_startup_detailed_description"),
    ]

    operations = [
        migrations.RenameField(
            model_name="professional",
            old_name="user",
            new_name="owner",
        ),
        migrations.AddField(
            model_name="professional",
            name="about",
            field=models.TextField(default="asd", verbose_name="Обо мне"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="professional",
            name="cv",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="image.file",
                verbose_name="Файл презентации",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="professional",
            name="email",
            field=models.EmailField(
                default="test@gmail.com", max_length=254, verbose_name="Email адрес"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="professional",
            name="lastName",
            field=models.CharField(
                default="shishkin", max_length=32, verbose_name="Фамилия"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="professional",
            name="name",
            field=models.CharField(default="alex", max_length=32, verbose_name="Имя"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="professional",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                default="+79997105576",
                max_length=128,
                region=None,
                verbose_name="Номер телефона",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="professional",
            name="photo",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="image.logo",
                verbose_name="Фото",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="professional",
            name="salary",
            field=models.TextField(default="2000", verbose_name="Зарплата"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="professional",
            name="skills",
            field=models.ManyToManyField(
                blank=True,
                related_name="skills",
                to="profiles.industries",
                verbose_name="Скилы",
            ),
        ),
    ]
