# Generated by Django 4.2 on 2023-05-01 13:08

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("image", "0012_alter_background_background_alter_logo_logo"),
        ("profiles", "0009_rename_user_professional_owner_professional_about_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="investor",
            old_name="user",
            new_name="owner",
        ),
        migrations.AddField(
            model_name="investor",
            name="about",
            field=models.TextField(default="test", verbose_name="Обо мне"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="investor",
            name="cv",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="image.file",
                verbose_name="Файл презентации",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="investor",
            name="interest",
            field=models.ManyToManyField(
                blank=True,
                related_name="interest",
                to="profiles.industries",
                verbose_name="Интересы",
            ),
        ),
        migrations.AddField(
            model_name="investor",
            name="lastName",
            field=models.CharField(
                default="alex", max_length=32, verbose_name="Фамилия"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="investor",
            name="name",
            field=models.CharField(default="test", max_length=32, verbose_name="Имя"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="investor",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                default="+79997105576",
                max_length=128,
                region=None,
                verbose_name="Номер телефона",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="investor",
            name="photo",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="image.logo",
                verbose_name="Фото",
            ),
            preserve_default=False,
        ),
    ]
