# Generated by Django 4.2 on 2023-05-02 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0010_rename_user_investor_owner_investor_about_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="professional",
            name="interest",
            field=models.ManyToManyField(
                blank=True,
                related_name="prof_interest",
                to="profiles.industries",
                verbose_name="Интересы",
            ),
        ),
        migrations.AlterField(
            model_name="investor",
            name="interest",
            field=models.ManyToManyField(
                blank=True,
                related_name="invest_interest",
                to="profiles.industries",
                verbose_name="Интересы",
            ),
        ),
    ]
