# Generated by Django 4.2 on 2023-05-04 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("image", "0012_alter_background_background_alter_logo_logo"),
        ("profiles", "0011_professional_interest_alter_investor_interest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="startup",
            name="already_distributed",
            field=models.IntegerField(
                blank=True, default=0, null=True, verbose_name="Ранние вложения"
            ),
        ),
        migrations.AlterField(
            model_name="startup",
            name="background",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="image.background",
                verbose_name="Бэкграунд",
            ),
        ),
        migrations.AlterField(
            model_name="startup",
            name="business_model",
            field=models.CharField(
                blank=True,
                choices=[
                    ("B2B", "Business to Business"),
                    ("B2C", "Business to consumer"),
                    ("B2G", "Business to Government"),
                    ("C2B", "Consumer to business"),
                    ("C2C", "Consumer to consumer"),
                    ("C2G", "Consumer to Government"),
                    ("SAAS", "Software on Demand"),
                ],
                max_length=25,
                null=True,
                verbose_name="Бизнес модель",
            ),
        ),
        migrations.AlterField(
            model_name="startup",
            name="capital_offer",
            field=models.IntegerField(
                blank=True, default=0, null=True, verbose_name="Предложение инвестору"
            ),
        ),
        migrations.AlterField(
            model_name="startup",
            name="detailed_description",
            field=models.TextField(
                blank=True, null=True, verbose_name="Детальное описание"
            ),
        ),
        migrations.AlterField(
            model_name="startup",
            name="headquartered",
            field=models.CharField(
                blank=True, max_length=32, null=True, verbose_name="Штаб-квартира"
            ),
        ),
        migrations.AlterField(
            model_name="startup",
            name="logo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="image.logo",
                verbose_name="Логотип",
            ),
        ),
        migrations.AlterField(
            model_name="startup",
            name="market_size",
            field=models.TextField(blank=True, null=True, verbose_name="Размер рынка"),
        ),
        migrations.AlterField(
            model_name="startup",
            name="pitch_presentation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="image.file",
                verbose_name="Файл презентации",
            ),
        ),
        migrations.AlterField(
            model_name="startup",
            name="purpose",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="profiles.purpose",
                verbose_name="Цель",
            ),
        ),
        migrations.AlterField(
            model_name="startup",
            name="regions",
            field=models.ManyToManyField(
                blank=True,
                related_name="sale_regions",
                to="profiles.saleregions",
                verbose_name="Регионы продажи",
            ),
        ),
        migrations.AlterField(
            model_name="startup",
            name="registration_country",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Northern America", "Северная Америка"),
                    ("Central America & Caribbean", "Центральная Америка и Карибы"),
                    ("South America", "Южная Америка"),
                    ("Nordics & Baltics", "Северо-Балтийск"),
                    ("Western Europe", "Западная Европа"),
                    ("Southern Europe", "Южная Европа"),
                    ("Eastern Europe & Russia", "Восточная Европа и Россия"),
                    (
                        "Northern Africa & Middle East",
                        "Северная Африка и Ближний Восток",
                    ),
                    ("Africa", "Африка"),
                    ("Asia", "Азия"),
                    ("Worldwide", "Мировой"),
                    (
                        "Australia, New Zealand & Oceania",
                        "Австралия, Новая зеландия и Океания",
                    ),
                ],
                max_length=50,
                null=True,
                verbose_name="Статус",
            ),
        ),
        migrations.AlterField(
            model_name="startup",
            name="required_founding",
            field=models.IntegerField(
                blank=True,
                default=0,
                null=True,
                verbose_name="Требуемое финансирование",
            ),
        ),
        migrations.AlterField(
            model_name="startup",
            name="social_links",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="profiles.links",
                verbose_name="Социальные сети",
            ),
        ),
    ]
