# Generated by Django 4.2 on 2023-05-04 07:40

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("image", "0012_alter_background_background_alter_logo_logo"),
        ("profiles", "0012_alter_startup_already_distributed_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="investor",
            name="email",
            field=models.EmailField(
                default="alexey@gmail.com", max_length=254, verbose_name="Email адрес"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="investor",
            name="social_links",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="profiles.links",
                verbose_name="Социальные сети",
            ),
        ),
        migrations.AlterField(
            model_name="investor",
            name="about",
            field=models.TextField(blank=True, null=True, verbose_name="Обо мне"),
        ),
        migrations.AlterField(
            model_name="investor",
            name="cv",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="image.file",
                verbose_name="Файл презентации",
            ),
        ),
        migrations.AlterField(
            model_name="investor",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                max_length=128,
                null=True,
                region=None,
                verbose_name="Номер телефона",
            ),
        ),
        migrations.AlterField(
            model_name="investor",
            name="photo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="image.logo",
                verbose_name="Фото",
            ),
        ),
        migrations.AlterField(
            model_name="professional",
            name="about",
            field=models.TextField(blank=True, null=True, verbose_name="Обо мне"),
        ),
        migrations.AlterField(
            model_name="professional",
            name="cv",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="image.file",
                verbose_name="Файл презентации",
            ),
        ),
        migrations.AlterField(
            model_name="professional",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                max_length=128,
                null=True,
                region=None,
                verbose_name="Номер телефона",
            ),
        ),
        migrations.AlterField(
            model_name="professional",
            name="photo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="image.logo",
                verbose_name="Фото",
            ),
        ),
        migrations.AlterField(
            model_name="professional",
            name="salary",
            field=models.TextField(blank=True, null=True, verbose_name="Зарплата"),
        ),
    ]
