# Generated by Django 4.2 on 2023-05-08 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0013_investor_email_investor_social_links_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="startup",
            name="business_model",
            field=models.CharField(
                blank=True,
                choices=[
                    ("b2b", "Business to Business"),
                    ("b2c", "Business to consumer"),
                    ("b2g", "Business to Government"),
                    ("c2b", "Consumer to business"),
                    ("c2c", "Consumer to consumer"),
                    ("c2g", "Consumer to Government"),
                    ("saas", "Software on Demand"),
                ],
                max_length=25,
                null=True,
                verbose_name="Бизнес модель",
            ),
        ),
        migrations.AlterField(
            model_name="startup",
            name="stage",
            field=models.CharField(
                choices=[("angel", "Ангел"), ("preSeed", "Пресид"), ("seed", "Сид")],
                max_length=10,
                verbose_name="Стадия",
            ),
        ),
    ]
