# Generated by Django 4.2 on 2023-05-08 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0014_alter_startup_business_model_alter_startup_stage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="startup",
            name="development_stage",
            field=models.CharField(
                choices=[
                    ("projectStart", "Старт проекта"),
                    ("workingOnTheProduct", "Работа над продуктом"),
                    ("enteringTheMarket", "Выход на рынок"),
                    ("growthAndScaling", "Рост и масштабирование"),
                ],
                max_length=32,
                verbose_name="Стадия разработки",
            ),
        ),
    ]
