# Generated by Django 4.2 on 2023-05-08 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("image", "0013_image"),
        ("profiles", "0015_alter_startup_development_stage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="investor",
            name="photo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="image.image",
                verbose_name="Фото",
            ),
        ),
        migrations.AlterField(
            model_name="professional",
            name="photo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="image.image",
                verbose_name="Фото",
            ),
        ),
        migrations.AlterField(
            model_name="startup",
            name="background",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="startup_background",
                to="image.image",
                verbose_name="Бэкграунд",
            ),
        ),
        migrations.AlterField(
            model_name="startup",
            name="logo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="startup_logo",
                to="image.image",
                verbose_name="Логотип",
            ),
        ),
    ]
