# Generated by Django 4.2 on 2023-05-10 09:09

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0016_alter_investor_photo_alter_professional_photo_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Resume",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_surname",
                    models.CharField(max_length=32, verbose_name="Имя-фамилия"),
                ),
                ("position", models.CharField(max_length=32, verbose_name="Позиция")),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None, verbose_name="Номер телефона"
                    ),
                ),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="Email адрес"),
                ),
                ("salary", models.IntegerField(verbose_name="Зарплата")),
                (
                    "about",
                    models.TextField(blank=True, null=True, verbose_name="Обо мне"),
                ),
                (
                    "education",
                    models.TextField(blank=True, null=True, verbose_name="Образование"),
                ),
                (
                    "work_experience",
                    models.TextField(blank=True, null=True, verbose_name="Опыт работы"),
                ),
                (
                    "professional_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profiles.professional",
                    ),
                ),
                (
                    "skills",
                    models.ManyToManyField(
                        blank=True,
                        related_name="resume_skills",
                        to="profiles.industries",
                        verbose_name="Скилы",
                    ),
                ),
            ],
        ),
    ]
