# Generated by Django 4.2 on 2023-05-10 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("image", "0014_delete_background_delete_logo_alter_file_pdf"),
        ("profiles", "0017_resume"),
    ]

    operations = [
        migrations.AddField(
            model_name="resume",
            name="cv",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="image.file",
                verbose_name="Файл презентации",
            ),
        ),
        migrations.AddField(
            model_name="resume",
            name="photo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="image.image",
                verbose_name="Фото",
            ),
        ),
    ]
