# Generated by Django 4.2 on 2023-05-10 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0018_resume_cv_resume_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="resume",
            name="link",
            field=models.CharField(
                blank=True, max_length=32, null=True, verbose_name="Ссылка"
            ),
        ),
    ]
