# Generated by Django 4.2 on 2023-05-10 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0019_resume_link"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="resume",
            name="professional_id",
        ),
        migrations.AddField(
            model_name="professional",
            name="resume",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prof_resume",
                to="profiles.resume",
            ),
        ),
    ]
