# Generated by Django 4.2 on 2023-05-10 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0020_remove_resume_professional_id_professional_resume"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="professional",
            name="resume",
        ),
        migrations.AddField(
            model_name="resume",
            name="professional_id",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="profiles.professional",
            ),
            preserve_default=False,
        ),
    ]
