# Generated by Django 4.2 on 2023-05-11 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0021_remove_professional_resume_resume_professional_id"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Resume",
        ),
    ]
