# Generated by Django 4.2 on 2023-05-11 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0022_delete_resume"),
    ]

    operations = [
        migrations.AddField(
            model_name="businesstype",
            name="description",
            field=models.TextField(default="test", verbose_name="Описание"),
            preserve_default=False,
        ),
    ]
