# Generated by Django 4.2 on 2023-05-16 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0024_alter_investor_owner_alter_professional_owner_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="businesstype",
            name="full_title",
            field=models.CharField(
                default="test", max_length=32, verbose_name="Полное название"
            ),
            preserve_default=False,
        ),
    ]
