# Generated by Django 4.2 on 2023-05-17 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vacancy", "0004_candidate"),
        ("profiles", "0025_businesstype_full_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="professional",
            name="applied_offers",
            field=models.ManyToManyField(
                blank=True,
                related_name="professional_applied_offers",
                to="vacancy.candidate",
                verbose_name="Подтвержденные оферы",
            ),
        ),
    ]
