# Generated by Django 4.2 on 2023-05-17 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0026_professional_applied_offers"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="professional",
            name="applied_offers",
        ),
    ]
