# Generated by Django 4.2 on 2023-05-17 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vacancy", "0008_remove_candidate_startup"),
        ("profiles", "0027_remove_professional_applied_offers"),
    ]

    operations = [
        migrations.AddField(
            model_name="startup",
            name="work_team",
            field=models.ManyToManyField(
                blank=True,
                related_name="startup_work_team",
                to="vacancy.candidate",
                verbose_name="Команда",
            ),
        ),
    ]
