# Generated by Django 4.2 on 2023-05-18 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0028_startup_work_team"),
    ]

    operations = [
        migrations.AlterField(
            model_name="startup",
            name="stage",
            field=models.CharField(
                choices=[
                    ("seed", "Основание"),
                    ("private", "Приват"),
                    ("strategic", "Стратеджик"),
                    ("public", "Паблик"),
                    ("secondaryFundraising", "Вторичное финансирование"),
                    ("noFundraisingRequired", "Финансирование не требуется"),
                ],
                max_length=32,
                verbose_name="Стадия",
            ),
        ),
    ]
