# Generated by Django 4.2 on 2023-05-22 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vacancy", "0012_workteam"),
        ("profiles", "0029_alter_startup_stage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="startup",
            name="work_team",
            field=models.ManyToManyField(
                blank=True,
                related_name="startup_work_team",
                to="vacancy.workteam",
                verbose_name="Команда",
            ),
        ),
    ]
