# Generated by Django 4.2 on 2023-05-24 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0030_alter_startup_work_team"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="startup",
            name="registration_country",
        ),
        migrations.AlterField(
            model_name="startup",
            name="development_stage",
            field=models.CharField(
                choices=[
                    ("projectStart", "Старт проекта"),
                    ("workingOnTheProject", "Работа над продуктом"),
                    ("enteringTheMarket", "Выход на рынок"),
                    ("growthAndScaling", "Рост и масштабирование"),
                ],
                max_length=32,
                verbose_name="Стадия разработки",
            ),
        ),
        migrations.AlterField(
            model_name="startup",
            name="profit",
            field=models.IntegerField(
                blank=True, default=0, null=True, verbose_name="Профит"
            ),
        ),
    ]
