# Generated by Django 4.2 on 2023-05-24 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0031_remove_startup_registration_country_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="startup",
            name="registration_country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="core_region",
                to="profiles.saleregions",
                verbose_name="Страна регистрации",
            ),
        ),
    ]
