# Generated by Django 4.2 on 2023-05-25 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0032_startup_registration_country"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="professional",
            name="interest",
        ),
        migrations.AddField(
            model_name="professional",
            name="speciality",
            field=models.CharField(
                default="tes", max_length=32, verbose_name="Специальность"
            ),
            preserve_default=False,
        ),
    ]
