# Generated by Django 4.2 on 2023-05-25 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0033_remove_professional_interest_professional_speciality"),
    ]

    operations = [
        migrations.AlterField(
            model_name="professional",
            name="speciality",
            field=models.CharField(
                blank=True, max_length=32, null=True, verbose_name="Специальность"
            ),
        ),
    ]
