# Generated by Django 4.2 on 2023-05-25 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0034_alter_professional_speciality"),
    ]

    operations = [
        migrations.AlterField(
            model_name="links",
            name="app_store",
            field=models.TextField(blank=True, null=True, verbose_name="Аппстор"),
        ),
        migrations.AlterField(
            model_name="links",
            name="discord",
            field=models.TextField(blank=True, null=True, verbose_name="Дискорд"),
        ),
        migrations.AlterField(
            model_name="links",
            name="facebook",
            field=models.TextField(blank=True, null=True, verbose_name="Фэйсбук"),
        ),
        migrations.AlterField(
            model_name="links",
            name="google_play",
            field=models.TextField(blank=True, null=True, verbose_name="Гуглплэй"),
        ),
        migrations.AlterField(
            model_name="links",
            name="instagram",
            field=models.TextField(blank=True, null=True, verbose_name="Инстаграм"),
        ),
        migrations.AlterField(
            model_name="links",
            name="linkedin",
            field=models.TextField(blank=True, null=True, verbose_name="Линкедин"),
        ),
        migrations.AlterField(
            model_name="links",
            name="medium",
            field=models.TextField(blank=True, null=True, verbose_name="Медиум"),
        ),
        migrations.AlterField(
            model_name="links",
            name="telegram",
            field=models.TextField(blank=True, null=True, verbose_name="Телеграм"),
        ),
        migrations.AlterField(
            model_name="links",
            name="twitter",
            field=models.TextField(blank=True, null=True, verbose_name="Твиттер"),
        ),
        migrations.AlterField(
            model_name="links",
            name="youtube",
            field=models.TextField(blank=True, null=True, verbose_name="Ютуб"),
        ),
    ]
