# Generated by Django 4.2 on 2023-05-25 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0035_alter_links_app_store_alter_links_discord_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="startup",
            name="url",
            field=models.TextField(blank=True, null=True, verbose_name="Урл"),
        ),
    ]
