# Generated by Django 4.2 on 2023-05-25 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("image", "0017_alter_file_pdf_alter_image_image"),
        ("profiles", "0036_alter_startup_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="investor",
            name="cv",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="image.file",
                verbose_name="Файл презентации",
            ),
        ),
        migrations.AlterField(
            model_name="investor",
            name="photo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="image.image",
                verbose_name="Фото",
            ),
        ),
        migrations.AlterField(
            model_name="investor",
            name="social_links",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="profiles.links",
                verbose_name="Социальные сети",
            ),
        ),
        migrations.AlterField(
            model_name="professional",
            name="cv",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="image.file",
                verbose_name="Файл презентации",
            ),
        ),
        migrations.AlterField(
            model_name="professional",
            name="photo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="image.image",
                verbose_name="Фото",
            ),
        ),
        migrations.AlterField(
            model_name="startup",
            name="achievements",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="profiles.achievements",
                verbose_name="Достижения",
            ),
        ),
        migrations.AlterField(
            model_name="startup",
            name="background",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="startup_background",
                to="image.image",
                verbose_name="Бэкграунд",
            ),
        ),
        migrations.AlterField(
            model_name="startup",
            name="logo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="startup_logo",
                to="image.image",
                verbose_name="Логотип",
            ),
        ),
        migrations.AlterField(
            model_name="startup",
            name="purpose",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="profiles.purpose",
                verbose_name="Цель",
            ),
        ),
        migrations.AlterField(
            model_name="startup",
            name="registration_country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="core_region",
                to="profiles.saleregions",
                verbose_name="Страна регистрации",
            ),
        ),
        migrations.AlterField(
            model_name="startup",
            name="social_links",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="profiles.links",
                verbose_name="Социальные сети",
            ),
        ),
    ]
