# Generated by Django 4.2 on 2023-06-05 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("image", "0017_alter_file_pdf_alter_image_image"),
        ("profiles", "0037_alter_investor_cv_alter_investor_photo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="startup",
            name="pitch_presentation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="image.file",
                verbose_name="Файл презентации",
            ),
        ),
    ]
