# Generated by Django 4.2 on 2023-07-04 09:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("profiles", "0038_alter_startup_pitch_presentation"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="achievements",
            options={"verbose_name": "Достижение", "verbose_name_plural": "Достижения"},
        ),
        migrations.AlterModelOptions(
            name="businesstype",
            options={
                "verbose_name": "Бизнес тип",
                "verbose_name_plural": "Бизнес типы",
            },
        ),
        migrations.AlterModelOptions(
            name="industries",
            options={"verbose_name": "Индустрия", "verbose_name_plural": "Индустрии"},
        ),
        migrations.AlterModelOptions(
            name="links",
            options={"verbose_name": "Url", "verbose_name_plural": "Urls"},
        ),
        migrations.AlterModelOptions(
            name="purpose",
            options={"verbose_name": "Цель", "verbose_name_plural": "Цели"},
        ),
        migrations.AlterModelOptions(
            name="saleregions",
            options={
                "verbose_name": "Регион продаж",
                "verbose_name_plural": "Регионы продаж",
            },
        ),
        migrations.AlterField(
            model_name="investor",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Владелец",
            ),
        ),
        migrations.AlterField(
            model_name="professional",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Владелец",
            ),
        ),
        migrations.AlterField(
            model_name="startup",
            name="foundation_year",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Год основания"
            ),
        ),
        migrations.AlterField(
            model_name="startup",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Владелец",
            ),
        ),
    ]
