# Generated by Django 4.2 on 2023-07-05 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0039_alter_achievements_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="startup",
            name="business_model",
        ),
        migrations.RemoveField(
            model_name="startup",
            name="market_size",
        ),
        migrations.RemoveField(
            model_name="startup",
            name="purpose",
        ),
    ]
