# Generated by Django 4.2 on 2023-04-23 07:39

from django.db import migrations, models
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ("image", "0002_remove_image_image_ppoi_remove_image_name_image_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="image",
            name="user",
        ),
        migrations.AddField(
            model_name="image",
            name="image_ppoi",
            field=versatileimagefield.fields.PPOIField(
                default="0.5x0.5", editable=False, max_length=20
            ),
        ),
        migrations.AddField(
            model_name="image",
            name="name",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
