# Generated by Django 4.2 on 2023-04-23 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("image", "0004_image_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="image",
            name="name",
        ),
        migrations.RemoveField(
            model_name="image",
            name="user",
        ),
    ]
