# Generated by Django 4.2 on 2023-04-23 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("image", "0006_logo"),
    ]

    operations = [
        migrations.CreateModel(
            name="File",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pdf", models.FileField(upload_to="pdf/")),
            ],
        ),
    ]
