# Generated by Django 4.2 on 2023-04-23 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("image", "0008_background_delete_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="logo",
            old_name="image",
            new_name="logo",
        ),
    ]
