# Generated by Django 4.2 on 2023-04-23 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("image", "0009_rename_image_logo_logo"),
    ]

    operations = [
        migrations.RenameField(
            model_name="background",
            old_name="image",
            new_name="background",
        ),
        migrations.RenameField(
            model_name="background",
            old_name="image_ppoi",
            new_name="background_ppoi",
        ),
    ]
