# Generated by Django 4.2 on 2023-04-30 09:29

from django.db import migrations, models
import image.validators


class Migration(migrations.Migration):

    dependencies = [
        ("image", "0010_rename_image_background_background_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="pdf",
            field=models.FileField(
                upload_to="pdf/",
                validators=[
                    image.validators.validate_file_size,
                    image.validators.validate_file_extension,
                ],
            ),
        ),
    ]
