# Generated by Django 4.2 on 2023-04-30 09:42

from django.db import migrations
import image.validators
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ("image", "0011_alter_file_pdf"),
    ]

    operations = [
        migrations.AlterField(
            model_name="background",
            name="background",
            field=versatileimagefield.fields.VersatileImageField(
                upload_to="backgrounds/",
                validators=[
                    image.validators.validate_image_extension,
                    image.validators.validate_image_size,
                ],
                verbose_name="Background",
            ),
        ),
        migrations.AlterField(
            model_name="logo",
            name="logo",
            field=versatileimagefield.fields.VersatileImageField(
                upload_to="logos/",
                validators=[
                    image.validators.validate_image_extension,
                    image.validators.validate_image_size,
                ],
                verbose_name="Logo",
            ),
        ),
    ]
