# Generated by Django 4.2 on 2023-05-08 12:56

from django.db import migrations, models
import image.validators
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ("image", "0012_alter_background_background_alter_logo_logo"),
    ]

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    versatileimagefield.fields.VersatileImageField(
                        upload_to="images/",
                        validators=[
                            image.validators.validate_image_extension,
                            image.validators.validate_image_size,
                        ],
                        verbose_name="Background",
                    ),
                ),
                (
                    "image_ppoi",
                    versatileimagefield.fields.PPOIField(
                        default="0.5x0.5", editable=False, max_length=20
                    ),
                ),
            ],
        ),
    ]
