# Generated by Django 4.2 on 2023-05-08 12:56

from django.db import migrations, models
import image.validators


class Migration(migrations.Migration):

    dependencies = [
        ("image", "0013_image"),
        ("articles", "0002_alter_article_image"),
        ("profiles", "0016_alter_investor_photo_alter_professional_photo_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Background",
        ),
        migrations.DeleteModel(
            name="Logo",
        ),
        migrations.AlterField(
            model_name="file",
            name="pdf",
            field=models.FileField(
                upload_to="files/",
                validators=[
                    image.validators.validate_file_size,
                    image.validators.validate_file_extension,
                ],
            ),
        ),
    ]
