# Generated by Django 4.2 on 2023-05-12 07:18

from django.db import migrations, models
import image.validators


class Migration(migrations.Migration):

    dependencies = [
        ("image", "0014_delete_background_delete_logo_alter_file_pdf"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="image",
            name="image_ppoi",
        ),
        migrations.AlterField(
            model_name="image",
            name="image",
            field=models.FileField(
                upload_to="images/",
                validators=[
                    image.validators.validate_image_extension,
                    image.validators.validate_image_size,
                ],
                verbose_name="Background",
            ),
        ),
    ]
