# Generated by Django 4.2 on 2023-05-15 09:32

from django.db import migrations, models
import image.validators


class Migration(migrations.Migration):

    dependencies = [
        ("image", "0015_remove_image_image_ppoi_alter_image_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="pdf",
            field=models.FileField(
                upload_to="files/", validators=[image.validators.validate_file_size]
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="image",
            field=models.FileField(
                upload_to="images/",
                validators=[image.validators.validate_image_size],
                verbose_name="Background",
            ),
        ),
    ]
