# Generated by Django 4.2 on 2023-05-17 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("image", "0016_alter_file_pdf_alter_image_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="pdf",
            field=models.FileField(upload_to="files/"),
        ),
        migrations.AlterField(
            model_name="image",
            name="image",
            field=models.FileField(upload_to="images/", verbose_name="Background"),
        ),
    ]
