# Generated by Django 4.2 on 2023-07-04 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("image", "0017_alter_file_pdf_alter_image_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="file",
            options={
                "verbose_name": "Файл презентации",
                "verbose_name_plural": "Файлы презентации",
            },
        ),
        migrations.AlterModelOptions(
            name="image",
            options={
                "verbose_name": "Изображение",
                "verbose_name_plural": "Изображения",
            },
        ),
    ]
