# Generated by Django 4.2 on 2023-05-05 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("profiles", "0013_investor_email_investor_social_links_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vacancy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.CharField(max_length=32, verbose_name="Позиция")),
                (
                    "requirements",
                    models.CharField(max_length=32, verbose_name="Требования"),
                ),
                ("is_active", models.BooleanField(verbose_name="Активен")),
                ("salary", models.IntegerField(verbose_name="Зарплата")),
                (
                    "company_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profiles.startup",
                    ),
                ),
            ],
        ),
    ]
