# Generated by Django 4.2 on 2023-05-05 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0013_investor_email_investor_social_links_and_more"),
        ("vacancy", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="vacancy",
            name="skills",
            field=models.ManyToManyField(
                blank=True,
                related_name="vacancy_skills",
                to="profiles.industries",
                verbose_name="Скилы",
            ),
        ),
    ]
