# Generated by Django 4.2 on 2023-05-10 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0021_remove_professional_resume_resume_professional_id"),
        ("vacancy", "0002_vacancy_skills"),
    ]

    operations = [
        migrations.CreateModel(
            name="Offer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.IntegerField(verbose_name="Кол-во инвестиций")),
                ("details", models.TextField(verbose_name="Детали")),
                (
                    "industries",
                    models.ManyToManyField(
                        blank=True,
                        related_name="offer_industries",
                        to="profiles.industries",
                        verbose_name="Индустрии",
                    ),
                ),
                (
                    "investor_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profiles.investor",
                    ),
                ),
            ],
        ),
    ]
