# Generated by Django 4.2 on 2023-05-17 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0026_professional_applied_offers"),
        ("vacancy", "0004_candidate"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="candidate",
            name="user_id",
        ),
        migrations.AddField(
            model_name="candidate",
            name="accept_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pendingforapproval", "Подал заявку"),
                    ("approve", "Подтвержден"),
                    ("intheteam", "В команде"),
                ],
                max_length=50,
                null=True,
                verbose_name="Статус",
            ),
        ),
        migrations.AddField(
            model_name="candidate",
            name="professional_id",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="profiles.professional",
            ),
            preserve_default=False,
        ),
    ]
