# Generated by Django 4.2 on 2023-05-17 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vacancy", "0005_remove_candidate_user_id_candidate_accept_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="base_status",
            field=models.CharField(
                blank=True,
                choices=[("new", "Новый"), ("viewed", "Просмотрен")],
                max_length=20,
                null=True,
                verbose_name="Статус просмотра",
            ),
        ),
    ]
