# Generated by Django 4.2 on 2023-05-17 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0026_professional_applied_offers"),
        ("vacancy", "0006_candidate_base_status"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="candidate",
            unique_together={("professional_id", "vacancy_id")},
        ),
    ]
