# Generated by Django 4.2 on 2023-05-17 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vacancy", "0007_alter_candidate_unique_together"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="candidate",
            name="startup",
        ),
    ]
