# Generated by Django 4.2 on 2023-05-18 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vacancy", "0008_remove_candidate_startup"),
    ]

    operations = [
        migrations.RenameField(
            model_name="vacancy",
            old_name="is_active",
            new_name="is_visible",
        ),
    ]
