# Generated by Django 4.2 on 2023-05-19 11:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("vacancy", "0009_rename_is_active_vacancy_is_visible"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Дата создания"
            ),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="accept_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pendingforapproval", "Подал заявку"),
                    ("accept", "Подтвержден"),
                    ("intheteam", "В команде"),
                ],
                max_length=50,
                null=True,
                verbose_name="Статус",
            ),
        ),
    ]
