# Generated by Django 4.2 on 2023-05-22 06:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("vacancy", "0010_candidate_created_at_alter_candidate_accept_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="offer",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Дата создания"
            ),
        ),
        migrations.AddField(
            model_name="vacancy",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Дата создания"
            ),
        ),
    ]
