# Generated by Django 4.2 on 2023-05-22 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("vacancy", "0011_offer_created_at_vacancy_created_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkTeam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "articles_and_news_management",
                    models.BooleanField(verbose_name="Изменение статей и новостей"),
                ),
                (
                    "company_management",
                    models.BooleanField(verbose_name="Изменение компании"),
                ),
                (
                    "vacancy_management",
                    models.BooleanField(verbose_name="Изменение статей"),
                ),
                (
                    "position",
                    models.CharField(
                        blank=True, max_length=32, null=True, verbose_name="Позиция"
                    ),
                ),
                (
                    "candidate_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vacancy.candidate",
                    ),
                ),
            ],
        ),
    ]
