# Generated by Django 4.2 on 2023-05-22 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vacancy", "0012_workteam"),
    ]

    operations = [
        migrations.AddField(
            model_name="workteam",
            name="performers_management",
            field=models.BooleanField(
                default=False, verbose_name="Возможность выдавать права"
            ),
        ),
        migrations.AlterField(
            model_name="workteam",
            name="articles_and_news_management",
            field=models.BooleanField(
                default=False, verbose_name="Изменение статей и новостей"
            ),
        ),
        migrations.AlterField(
            model_name="workteam",
            name="company_management",
            field=models.BooleanField(default=False, verbose_name="Изменение компании"),
        ),
        migrations.AlterField(
            model_name="workteam",
            name="vacancy_management",
            field=models.BooleanField(default=False, verbose_name="Изменение статей"),
        ),
    ]
