# Generated by Django 4.2 on 2023-05-30 14:13

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("vacancy", "0013_workteam_performers_management_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vacancy",
            name="created_at",
            field=django_extensions.db.fields.CreationDateTimeField(
                auto_now_add=True, verbose_name="Дата создания"
            ),
        ),
    ]
