# Generated by Django 4.2 on 2023-05-31 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vacancy", "0014_alter_vacancy_created_at"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Offer",
        ),
    ]
