# Generated by Django 4.2 on 2023-05-31 11:47

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("vacancy", "0015_delete_offer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidate",
            name="created_at",
            field=django_extensions.db.fields.CreationDateTimeField(
                auto_now_add=True, verbose_name="Дата создания"
            ),
        ),
    ]
