# Generated by Django 4.2 on 2023-06-05 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0037_alter_investor_cv_alter_investor_photo_and_more"),
        ("vacancy", "0016_alter_candidate_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="workteam",
            name="startup_id",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="profiles.startup",
            ),
            preserve_default=False,
        ),
    ]
