# Generated by Django 4.2 on 2023-06-05 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0037_alter_investor_cv_alter_investor_photo_and_more"),
        ("vacancy", "0017_workteam_startup_id"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="workteam",
            unique_together={("startup_id", "candidate_id")},
        ),
    ]
