# Generated by Django 4.2 on 2023-06-07 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vacancy", "0018_alter_workteam_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="vacancy",
            name="description",
            field=models.TextField(default="text", verbose_name="Описание"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="vacancy",
            name="place",
            field=models.CharField(
                choices=[("office", "офис"), ("remote", "дистанционная работа")],
                default="office",
                max_length=32,
                verbose_name="Рабочая локация",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="vacancy",
            name="salary_type",
            field=models.CharField(
                choices=[
                    ("hourly", "почасовая"),
                    ("monthly", "ежемесячно"),
                    ("annual", "ежегодно"),
                    ("perProject", "за проект"),
                ],
                default="monthly",
                max_length=32,
                verbose_name="Вид оплаты",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="vacancy",
            name="work_schedude",
            field=models.CharField(
                choices=[
                    ("fullTime", "полная занятость"),
                    ("partTime", "частичная занятость"),
                ],
                default="fullTime",
                max_length=32,
                verbose_name="Тип занятости",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="requirements",
            field=models.TextField(verbose_name="Требования"),
        ),
    ]
