# Generated by Django 4.2 on 2023-06-07 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vacancy", "0019_vacancy_description_vacancy_place_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="is_favorite",
            field=models.BooleanField(default=0, verbose_name="В избранных"),
            preserve_default=False,
        ),
    ]
