# Generated by Django 4.2 on 2023-06-09 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vacancy", "0020_candidate_is_favorite"),
    ]

    operations = [
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=32, verbose_name="Заголовок")),
            ],
        ),
        migrations.RemoveField(
            model_name="vacancy",
            name="skills",
        ),
    ]
