# Generated by Django 4.2 on 2023-06-09 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vacancy", "0021_skill_remove_vacancy_skills"),
    ]

    operations = [
        migrations.AddField(
            model_name="vacancy",
            name="skills",
            field=models.ManyToManyField(
                blank=True, related_name="vacancy_skills", to="vacancy.skill"
            ),
        ),
    ]
