# Generated by Django 4.2 on 2023-06-09 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vacancy", "0022_vacancy_skills"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="about",
            field=models.TextField(default="about", verbose_name="Обо мне"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="candidate",
            name="accept_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("decline", "Отклонен"),
                    ("pendingforapproval", "Подал заявку"),
                    ("intheteam", "В команде"),
                ],
                max_length=50,
                null=True,
                verbose_name="Статус",
            ),
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="place",
            field=models.CharField(
                choices=[
                    ("office", "офис"),
                    ("remote", "дистанционная работа"),
                    ("mixed", "смешанный тип работы"),
                ],
                max_length=32,
                verbose_name="Рабочая локация",
            ),
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="salary",
            field=models.IntegerField(blank=True, null=True, verbose_name="Зарплата"),
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="salary_type",
            field=models.CharField(
                choices=[
                    ("hourly", "почасовая"),
                    ("monthly", "ежемесячно"),
                    ("annual", "ежегодно"),
                    ("perProject", "за проект"),
                    ("percent", "процент"),
                ],
                max_length=32,
                verbose_name="Вид оплаты",
            ),
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="work_schedude",
            field=models.CharField(
                choices=[
                    ("fullTime", "полная занятость"),
                    ("partTime", "частичная занятость"),
                    ("project", "проектная занятость"),
                ],
                max_length=32,
                verbose_name="Тип занятости",
            ),
        ),
    ]
