# Generated by Django 4.2 on 2023-06-20 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vacancy", "0023_candidate_about_alter_candidate_accept_status_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Requirement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=32, verbose_name="Заголовок")),
            ],
        ),
        migrations.RemoveField(
            model_name="vacancy",
            name="requirements",
        ),
        migrations.AddField(
            model_name="vacancy",
            name="requirements",
            field=models.ManyToManyField(
                blank=True,
                related_name="vacancy_requirements",
                to="vacancy.requirement",
            ),
        ),
    ]
