# Generated by Django 4.2 on 2023-06-26 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vacancy", "0024_requirement_remove_vacancy_requirements_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="vacancy",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddIndex(
            model_name="vacancy",
            index=models.Index(
                fields=["-created_at"], name="vacancy_vac_created_799e85_idx"
            ),
        ),
    ]
