# Generated by Django 4.2 on 2023-06-26 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vacancy", "0025_alter_vacancy_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="requirement",
            name="title",
            field=models.TextField(verbose_name="Заголовок"),
        ),
        migrations.AlterField(
            model_name="skill",
            name="title",
            field=models.CharField(max_length=54, verbose_name="Заголовок"),
        ),
    ]
