# Generated by Django 4.2 on 2023-06-26 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vacancy", "0026_alter_requirement_title_alter_skill_title"),
    ]

    operations = [
        migrations.RenameField(
            model_name="vacancy",
            old_name="work_schedude",
            new_name="work_schedule",
        ),
    ]
