# Generated by Django 4.2 on 2023-06-28 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0038_alter_startup_pitch_presentation"),
        ("vacancy", "0027_rename_work_schedude_vacancy_work_schedule"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidate",
            name="professional_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="candidate_professional",
                to="profiles.professional",
            ),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="vacancy_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="candidate_vacancy",
                to="vacancy.vacancy",
            ),
        ),
    ]
