# Generated by Django 4.2 on 2023-07-04 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0039_alter_achievements_options_and_more"),
        ("vacancy", "0028_alter_candidate_professional_id_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="candidate",
            options={"verbose_name": "Кандидат", "verbose_name_plural": "Кандидаты"},
        ),
        migrations.AlterModelOptions(
            name="requirement",
            options={"verbose_name": "Требование", "verbose_name_plural": "Требования"},
        ),
        migrations.AlterModelOptions(
            name="skill",
            options={"verbose_name": "Умение", "verbose_name_plural": "Умения"},
        ),
        migrations.AlterModelOptions(
            name="vacancy",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Вакансия",
                "verbose_name_plural": "Вакансии",
            },
        ),
        migrations.AlterModelOptions(
            name="workteam",
            options={
                "verbose_name": "Член команды",
                "verbose_name_plural": "Члены команды",
            },
        ),
        migrations.AlterField(
            model_name="candidate",
            name="professional_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="candidate_professional",
                to="profiles.professional",
                verbose_name="Профессионал",
            ),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="vacancy_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="candidate_vacancy",
                to="vacancy.vacancy",
                verbose_name="Вакансия",
            ),
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="company_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="profiles.startup",
                verbose_name="Владелец",
            ),
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="is_visible",
            field=models.BooleanField(verbose_name="Активна"),
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="requirements",
            field=models.ManyToManyField(
                blank=True,
                related_name="vacancy_requirements",
                to="vacancy.requirement",
                verbose_name="Требования",
            ),
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="skills",
            field=models.ManyToManyField(
                blank=True,
                related_name="vacancy_skills",
                to="vacancy.skill",
                verbose_name="Навыки",
            ),
        ),
        migrations.AlterField(
            model_name="workteam",
            name="candidate_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="vacancy.candidate",
                verbose_name="Кандидат",
            ),
        ),
        migrations.AlterField(
            model_name="workteam",
            name="startup_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="profiles.startup",
                verbose_name="Стартап",
            ),
        ),
    ]
