# Generated by Django 4.2 on 2023-07-18 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vacancy", "0029_alter_candidate_options_alter_requirement_options_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="candidate",
            unique_together=set(),
        ),
    ]
