# Generated by Django 4.2 on 2023-07-18 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0040_remove_startup_business_model_and_more"),
        ("vacancy", "0030_alter_candidate_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="candidate",
            unique_together={("professional_id", "vacancy_id")},
        ),
    ]
