# Generated by Django 4.2 on 2023-07-19 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vacancy", "0031_alter_candidate_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidate",
            name="accept_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("concluded", "Исключен из команды"),
                    ("decline", "Отклонен"),
                    ("pendingforapproval", "Подал заявку"),
                    ("intheteam", "В команде"),
                ],
                max_length=50,
                null=True,
                verbose_name="Статус",
            ),
        ),
    ]
