# Generated by Django 4.2 on 2023-08-23 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("vacancy", "0032_alter_candidate_accept_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidate",
            name="vacancy_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="candidate_vacancy",
                to="vacancy.vacancy",
                verbose_name="Вакансия",
            ),
        ),
    ]
