# Generated by Django 4.2 on 2023-08-24 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vacancy", "0033_alter_candidate_vacancy_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="vacancy",
            name="active_status",
            field=models.CharField(
                choices=[("active", "активна"), ("archive", "в архиве")],
                default=1,
                max_length=32,
                verbose_name="Активный статус",
            ),
            preserve_default=False,
        ),
    ]
