# Generated by Django 4.2 on 2023-09-01 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vacancy", "0035_alter_candidate_accept_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidate",
            name="accept_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("deleted", "Удалился"),
                    ("concluded", "Исключен из команды"),
                    ("decline", "Отклонен"),
                    ("pendingforapproval", "Подал заявку"),
                    ("intheteam", "В команде"),
                    ("thevacancyisnotcurrent", "Вакансия более не существует"),
                ],
                max_length=50,
                null=True,
                verbose_name="Статус",
            ),
        ),
    ]
