from django.urls import path

from offer.views import (
    OfferListCreateView,
    OfferRetrieveUpdateDeleteView,
    AllOffersList,
    AllOffersRetrieve,
    OfferVisibleRetrieveView,
    StartupCandidateCreateView,
    ListAllOfferCandidates,
    OfferRetrieveStartupCandidates,
    OfferStartupCandidates,
    ConfirmOfferView,
    InvestorConfirmedStartupsList,
    StartupConfirmedList,
    InvestorAllOffers,
)


urlpatterns = [
    path(
        "main/offers/",
        OfferListCreateView.as_view(),
        name="list_create_offer",
    ),
    path(
        "main/offers/<int:pk>/",
        OfferRetrieveUpdateDeleteView.as_view(),
        name="retrieve_offer",
    ),
    path(
        "main/offers/<int:pk>/visible/",
        OfferVisibleRetrieveView.as_view(),
        name="visible_retrieve_offer",
    ),
    path(
        "main/offers/startups/",
        OfferStartupCandidates.as_view(),
        name="all_startups_to_investor",
    ),
    path(
        "main/offers/startups/<int:pk>/",
        OfferRetrieveStartupCandidates.as_view(),
        name="retrieve_delete_startup_to_offer",
    ),
    path(
        "main/offers/<int:pk>/startups/",
        ListAllOfferCandidates.as_view(),
        name="all_startups_to_offer",
    ),
    path(
        "main/offers/<int:pk>/confirm/",
        ConfirmOfferView.as_view(),
        name="confirm_investing_to_startup",
    ),
    path(
        "main/confirmed_offers/",
        InvestorConfirmedStartupsList.as_view(),
        name="all_confirmed_offers",
    ),
    path("common/offers/", AllOffersList.as_view(), name="all_offers"),
    path(
        "common/offers/<int:pk>/",
        AllOffersRetrieve.as_view(),
        name="all_detail_offers",
    ),
    path(
        "common/investor/<int:pk>/offers/",
        InvestorAllOffers.as_view(),
        name="all_offers_to_investor",
    ),
    path(
        "common/offers/<int:pk>/apply/",
        StartupCandidateCreateView.as_view(),
        name="apply_startup_to_offer",
    ),
    path(
        "main/startup/investors/",
        StartupConfirmedList.as_view(),
        name="all_startup_investors_list",
    ),
]
