# Generated by Django 4.2 on 2023-05-19 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0002_alter_article_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="is_visible",
            field=models.BooleanField(default=1, verbose_name="Видим"),
            preserve_default=False,
        ),
    ]
