# Generated by Django 4.2 on 2023-05-19 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0003_article_is_visible"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="view_count",
            field=models.IntegerField(default=0),
        ),
    ]
