# Generated by Django 4.2 on 2023-05-25 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("image", "0017_alter_file_pdf_alter_image_image"),
        ("articles", "0005_article_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="image.image",
                verbose_name="Фото",
            ),
        ),
    ]
