# Generated by Django 4.2 on 2023-05-30 14:13

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0006_alter_article_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=32, verbose_name="Заголовок")),
            ],
        ),
        migrations.AlterField(
            model_name="article",
            name="created_at",
            field=django_extensions.db.fields.CreationDateTimeField(
                auto_now_add=True, verbose_name="Дата создания"
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="tags",
            field=models.ManyToManyField(
                related_name="article_tags", to="articles.tag"
            ),
        ),
    ]
