# Generated by Django 4.2 on 2023-05-31 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0007_tag_alter_article_created_at_article_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="view_count",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
