# Generated by Django 4.2 on 2023-06-02 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0009_alter_article_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="article_tags", to="articles.tag"
            ),
        ),
    ]
