# Generated by Django 4.2 on 2023-06-26 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0010_alter_article_tags"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="article",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(
                fields=["-created_at"], name="articles_ar_created_312397_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(
                fields=["-view_count"], name="articles_ar_view_co_f1b57c_idx"
            ),
        ),
    ]
