# Generated by Django 4.2 on 2023-06-27 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("image", "0017_alter_file_pdf_alter_image_image"),
        ("profiles", "0038_alter_startup_pitch_presentation"),
        ("articles", "0011_alter_article_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="company_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="article_company",
                to="profiles.startup",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="article_image",
                to="image.image",
                verbose_name="Фото",
            ),
        ),
    ]
