# Generated by Django 4.2 on 2023-07-04 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0039_alter_achievements_options_and_more"),
        ("articles", "0012_alter_article_company_id_alter_article_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="article",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Статья",
                "verbose_name_plural": "Статьи",
            },
        ),
        migrations.AlterModelOptions(
            name="tag",
            options={"verbose_name": "Тег", "verbose_name_plural": "Теги"},
        ),
        migrations.AlterField(
            model_name="article",
            name="company_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="article_company",
                to="profiles.startup",
                verbose_name="Владелец",
            ),
        ),
    ]
