# Generated by Django 4.2 on 2023-07-05 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0013_alter_article_options_alter_tag_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tag",
            options={
                "verbose_name": "Scope of Interest",
                "verbose_name_plural": "Scope of Interests",
            },
        ),
        migrations.AlterField(
            model_name="tag",
            name="title",
            field=models.CharField(max_length=52, verbose_name="Заголовок"),
        ),
    ]
