# Generated by Django 4.2 on 2023-09-18 06:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("image", "0018_alter_file_options_alter_image_options"),
        ("profiles", "0040_remove_startup_business_model_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Network",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(blank=True, null=True, verbose_name="Активен"),
                ),
                ("about", models.TextField(verbose_name="О себе")),
                (
                    "interest",
                    models.ManyToManyField(
                        blank=True,
                        related_name="scope_of_interest",
                        to="profiles.industries",
                        verbose_name="Интересы",
                    ),
                ),
                (
                    "logo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="network_logo",
                        to="image.image",
                        verbose_name="Фото профиля",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="network_owner",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Владелец аккаунта",
                    ),
                ),
            ],
            options={
                "verbose_name": "Network",
                "verbose_name_plural": "Networks",
            },
        ),
    ]
