# Generated by Django 4.2 on 2023-09-18 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="network",
            old_name="interest",
            new_name="interests",
        ),
    ]
