# Generated by Django 4.2 on 2023-09-18 07:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("network", "0002_rename_interest_network_interests"),
    ]

    operations = [
        migrations.AlterField(
            model_name="network",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="network_owner",
                to=settings.AUTH_USER_MODEL,
                unique=True,
                verbose_name="Владелец аккаунта",
            ),
        ),
    ]
