# Generated by Django 4.2 on 2023-09-19 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0004_alter_network_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="network",
            name="connect_network",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="network.network",
                verbose_name="Сопряженный Network",
            ),
        ),
    ]
