# Generated by Django 4.2 on 2023-04-17 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_user_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile",
            field=models.CharField(
                choices=[
                    ("startup", "Стартап"),
                    ("investor", "Инвестор"),
                    ("professional", "Профессионал"),
                ],
                default=1,
                max_length=12,
                verbose_name="Профиль",
            ),
            preserve_default=False,
        ),
    ]
