# Generated by Django 4.2 on 2023-04-17 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_user_profile"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="profile",
            new_name="name_profile",
        ),
    ]
