# Generated by Django 4.2 on 2023-04-17 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_rename_profile_user_name_profile"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="name_profile",
            new_name="profile",
        ),
    ]
