# Generated by Django 4.2 on 2023-04-19 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_alter_user_options_user_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="code",
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
