# Generated by Django 4.2 on 2023-04-23 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("image", "0001_initial"),
        ("core", "0009_user_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="image",
            field=models.ManyToManyField(related_name="images", to="image.image"),
        ),
    ]
