# Generated by Django 4.2 on 2023-04-23 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_user_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="image",
        ),
    ]
