# Generated by Django 4.2 on 2023-04-23 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("image", "0003_remove_image_user_image_image_ppoi_image_name"),
        ("core", "0011_remove_user_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="image",
            field=models.ManyToManyField(related_name="products", to="image.image"),
        ),
    ]
