# Generated by Django 4.2 on 2023-05-11 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_remove_user_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_onboarding",
            field=models.BooleanField(default=1, verbose_name="Онбоардинг"),
            preserve_default=False,
        ),
    ]
