# Generated by Django 4.2 on 2023-05-24 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_user_is_onboarding"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_onboarding",
            field=models.BooleanField(blank=True, null=True, verbose_name="Онбоардинг"),
        ),
    ]
