# Generated by Django 4.2 on 2023-06-05 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("vacancy", "0016_alter_candidate_created_at"),
        ("core", "0015_alter_user_is_onboarding"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="permissions",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="vacancy.workteam",
            ),
            preserve_default=False,
        ),
    ]
