# Generated by Django 4.2 on 2023-06-05 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("vacancy", "0018_alter_workteam_unique_together"),
        ("core", "0015_alter_user_is_onboarding"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="permissions",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="vacancy.workteam",
            ),
        ),
    ]
