# Generated by Django 4.2 on 2023-06-05 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("vacancy", "0017_workteam_startup_id"),
        ("core", "0016_user_permissions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="permissions",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="vacancy.workteam",
            ),
        ),
    ]
