# Generated by Django 4.2 on 2023-06-30 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_alter_user_permissions"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="online",
            field=models.BooleanField(default=0, verbose_name="Онлайн статус"),
            preserve_default=False,
        ),
    ]
