# Generated by Django 4.2 on 2023-07-04 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_user_online"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="online",
            field=models.BooleanField(default=False, verbose_name="Онлайн статус"),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                blank=True,
                help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                max_length=150,
                verbose_name="username",
            ),
        ),
    ]
