# Generated by Django 4.2 on 2023-08-11 12:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_alter_user_online_alter_user_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="users_banned_list",
            field=models.ManyToManyField(
                blank=True,
                related_name="user_banned_list",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Забаненные пользователи",
            ),
        ),
    ]
