# Generated by Django 4.2 on 2023-09-01 11:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_user_users_banned_list"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="users_banned_list",
            field=models.ManyToManyField(
                blank=True,
                related_name="user_two_banned_list",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Забаненные пользователи",
            ),
        ),
    ]
