# Generated by Django 4.2 on 2023-09-04 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_alter_user_users_banned_list"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="spam_count",
            field=models.PositiveIntegerField(
                blank=True, default=0, null=True, verbose_name="Кол-во жалоб"
            ),
        ),
    ]
