# Generated by Django 4.2 on 2023-05-31 06:55

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("profiles", "0037_alter_investor_cv_alter_investor_photo_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Offer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.IntegerField(verbose_name="Кол-во инвестиций")),
                ("details", models.TextField(verbose_name="Детали")),
                (
                    "created_at",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "industries",
                    models.ManyToManyField(
                        blank=True,
                        related_name="offer_industries",
                        to="profiles.industries",
                        verbose_name="Индустрии",
                    ),
                ),
                (
                    "investor_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profiles.investor",
                    ),
                ),
            ],
        ),
    ]
