# Generated by Django 4.2 on 2023-05-31 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("offer", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="offer",
            name="is_visible",
            field=models.BooleanField(default=1, verbose_name="Активен"),
            preserve_default=False,
        ),
    ]
