# Generated by Django 4.2 on 2023-05-31 11:47

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0037_alter_investor_cv_alter_investor_photo_and_more"),
        ("offer", "0002_offer_is_visible"),
    ]

    operations = [
        migrations.CreateModel(
            name="CandidateStartup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "accept_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("pendingforapproval", "Подал заявку"),
                            ("accept", "Подтвержден"),
                        ],
                        max_length=50,
                        null=True,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "created_at",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "offer_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="offer.offer"
                    ),
                ),
                (
                    "startup_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profiles.startup",
                    ),
                ),
            ],
            options={
                "unique_together": {("startup_id", "offer_id")},
            },
        ),
    ]
