# Generated by Django 4.2 on 2023-06-02 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0037_alter_investor_cv_alter_investor_photo_and_more"),
        ("offer", "0003_candidatestartup"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidatestartup",
            name="offer_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="offer.offer",
            ),
        ),
        migrations.AlterField(
            model_name="candidatestartup",
            name="startup_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="profiles.startup",
            ),
        ),
    ]
