# Generated by Django 4.2 on 2023-06-02 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0037_alter_investor_cv_alter_investor_photo_and_more"),
        ("offer", "0004_alter_candidatestartup_offer_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidatestartup",
            name="offer_id",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="offer.offer"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="candidatestartup",
            name="startup_id",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="profiles.startup",
            ),
            preserve_default=False,
        ),
    ]
