# Generated by Django 4.2 on 2023-06-02 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0037_alter_investor_cv_alter_investor_photo_and_more"),
        ("offer", "0005_alter_candidatestartup_offer_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfirmedOffer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "investor_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profiles.investor",
                    ),
                ),
                (
                    "startup_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profiles.startup",
                    ),
                ),
            ],
            options={
                "unique_together": {("startup_id", "investor_id")},
            },
        ),
    ]
