# Generated by Django 4.2 on 2023-07-04 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0039_alter_achievements_options_and_more"),
        ("offer", "0006_confirmedoffer"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="confirmedoffer",
            options={
                "verbose_name": "Подтвержденный офер",
                "verbose_name_plural": "Подтвержденные оферы",
            },
        ),
        migrations.AlterModelOptions(
            name="offer",
            options={"verbose_name": "Офер", "verbose_name_plural": "Оферы"},
        ),
        migrations.AlterField(
            model_name="offer",
            name="investor_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="profiles.investor",
                verbose_name="Владелец",
            ),
        ),
    ]
