# Generated by Django 4.2 on 2023-07-25 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vacancy", "0032_alter_candidate_accept_status"),
        ("offer", "0007_alter_confirmedoffer_options_alter_offer_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="offer",
            name="details",
        ),
        migrations.AddField(
            model_name="candidatestartup",
            name="about",
            field=models.TextField(default="about", verbose_name="Обо мне"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="offer",
            name="caption",
            field=models.CharField(
                default="caption", max_length=128, verbose_name="Заголовок"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="offer",
            name="offer_information",
            field=models.TextField(
                default="information", verbose_name="Информация о офере"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="offer",
            name="industries",
            field=models.ManyToManyField(
                blank=True,
                related_name="offer_industries",
                to="vacancy.skill",
                verbose_name="Индустрии",
            ),
        ),
    ]
