# Generated by Django 4.2 on 2023-07-25 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("offer", "0008_remove_offer_details_candidatestartup_about_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidatestartup",
            name="is_favorite",
            field=models.BooleanField(default=0, verbose_name="В избранных"),
            preserve_default=False,
        ),
    ]
