# Generated by Django 4.2 on 2023-07-31 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("offer", "0009_candidatestartup_is_favorite"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidatestartup",
            name="accept_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("concluded", "Исключен"),
                    ("pendingforapproval", "Подал заявку"),
                    ("accept", "Подтвержден"),
                ],
                max_length=50,
                null=True,
                verbose_name="Статус",
            ),
        ),
    ]
