# Generated by Django 4.2 on 2023-07-31 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("offer", "0010_alter_candidatestartup_accept_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="confirmedoffer",
            name="offer_id",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="offer.offer"
            ),
            preserve_default=False,
        ),
    ]
