# Generated by Django 4.2 on 2023-07-31 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("offer", "0011_confirmedoffer_offer_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="confirmedoffer",
            name="offer_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="offer.offer",
            ),
        ),
    ]
