# Generated by Django 4.2 on 2023-07-31 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0040_remove_startup_business_model_and_more"),
        ("offer", "0012_alter_confirmedoffer_offer_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidatestartup",
            name="offer_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="offer_to_candidate",
                to="offer.offer",
            ),
        ),
        migrations.AlterField(
            model_name="candidatestartup",
            name="startup_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="startup_to_offer",
                to="profiles.startup",
            ),
        ),
    ]
