# Generated by Django 4.2 on 2023-08-01 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0040_remove_startup_business_model_and_more"),
        ("offer", "0013_alter_candidatestartup_offer_id_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="confirmedoffer",
            unique_together={("startup_id", "offer_id")},
        ),
    ]
