# Generated by Django 4.2 on 2023-08-01 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("offer", "0014_alter_confirmedoffer_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidatestartup",
            name="accept_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("decline", "Отклонен"),
                    ("concluded", "Исключен"),
                    ("pendingforapproval", "Подал заявку"),
                    ("accept", "Подтвержден"),
                ],
                max_length=50,
                null=True,
                verbose_name="Статус",
            ),
        ),
    ]
