# Generated by Django 4.2 on 2023-08-24 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("offer", "0015_alter_candidatestartup_accept_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidatestartup",
            name="offer_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="offer_to_candidate",
                to="offer.offer",
            ),
        ),
    ]
