# Generated by Django 4.2 on 2023-08-28 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("offer", "0016_alter_candidatestartup_offer_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="offer",
            name="active_status",
            field=models.CharField(
                choices=[("active", "активен"), ("archive", "в архиве")],
                default=1,
                max_length=32,
                verbose_name="Активный статус",
            ),
            preserve_default=False,
        ),
    ]
