# Generated by Django 4.2 on 2023-08-28 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("offer", "0017_offer_active_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidatestartup",
            name="accept_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("decline", "Отклонен"),
                    ("concluded", "Исключен"),
                    ("pendingforapproval", "Подал заявку"),
                    ("accept", "Подтвержден"),
                    ("theofferisoutoforder", "Предложение недействительно"),
                ],
                max_length=50,
                null=True,
                verbose_name="Статус",
            ),
        ),
    ]
