# Generated by Django 4.2 on 2023-09-01 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("offer", "0018_alter_candidatestartup_accept_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidatestartup",
            name="accept_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("deleted", "Удалился"),
                    ("decline", "Отклонен"),
                    ("concluded", "Исключен"),
                    ("pendingforapproval", "Подал заявку"),
                    ("accept", "Подтвержден"),
                    ("theofferisoutoforder", "Предложение недействительно"),
                ],
                max_length=50,
                null=True,
                verbose_name="Статус",
            ),
        ),
    ]
